### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by brauliobo** [seblu/agetpkg#2]
Can install using `sudo pacman -S agetpkg` :(

**Comment by HLFH** [comment]
Same :'(

**Comment by jaltek** [comment]
See https://lists.archlinux.org/pipermail/arch-dev-public/2015-October/027480.html.

Try to clone the repo and install via `makepkg -i` as mentioned in the README.

**Comment by HLFH** [comment]
@jaltek That's what I've done but we want `agetpkg` in AUR.

**Comment by jaltek** [comment]
@seblu Are there any concerns to put it to AUR? I could maintain the package...

**Comment by HLFH** [comment]
@brauliobo @jaltek @seblu [Done](https://aur.archlinux.org/packages/agetpkg-git/). You can do `pacaur -S agetpkg-git` or `yaourt -S agetpkg-git`

**Comment by jaltek** [comment]
:thumbsup:
